//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johan.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BagTransaction
    {
        public long ID { get; set; }
        public Nullable<int> partyId { get; set; }
        public Nullable<long> rcvId { get; set; }
        public Nullable<int> comRcvBag { get; set; }
        public Nullable<double> rcvPrice { get; set; }
        public Nullable<int> comSentBag { get; set; }
        public Nullable<double> sentPrice { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> bagDues { get; set; }
        public Nullable<double> priceDues { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual tblParty tblParty { get; set; }
        public virtual tblBuy tblBuy { get; set; }
    }
}
