//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johan.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.SalaryPayments = new HashSet<SalaryPayment>();
        }
    
        public long ID { get; set; }
        public string empName { get; set; }
        public string address { get; set; }
        public string designation { get; set; }
        public string contact { get; set; }
        public System.DateTime joiningDate { get; set; }
        public double currentSalary { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual ICollection<SalaryPayment> SalaryPayments { get; set; }
    }
}
