//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johan.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaddyTransaction
    {
        public long ID { get; set; }
        public double openingStock { get; set; }
        public int stockId { get; set; }
        public int prodId { get; set; }
        public Nullable<double> rcvQty { get; set; }
        public Nullable<double> releaseQty { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<long> buyId { get; set; }
        public Nullable<double> bagWeight { get; set; }
        public Nullable<double> millCost { get; set; }
        public Nullable<int> serial { get; set; }
        public Nullable<int> fromStock { get; set; }
    }
}
