//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johan.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryPayment
    {
        public long ID { get; set; }
        public long empId { get; set; }
        public double paidAmount { get; set; }
        public string month { get; set; }
        public decimal year { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
