//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johan.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK_Balance
    {
        public int ID { get; set; }
        public Nullable<int> stockId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<double> sackQuantity { get; set; }
        public Nullable<double> sackWeight { get; set; }
    
        public virtual STK_tblStock STK_tblStock { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
