//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johan.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCostingSource
    {
        public tblCostingSource()
        {
            this.tblDues = new HashSet<tblDue>();
        }
    
        public long ID { get; set; }
        public Nullable<int> partyId { get; set; }
        public double amount { get; set; }
        public string sourceName { get; set; }
        public string srcDescription { get; set; }
        public int srcDescId { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<long> sellId { get; set; }
        public Nullable<long> buyId { get; set; }
        public Nullable<double> labourCostPerBag { get; set; }
        public Nullable<double> transportCost { get; set; }
        public Nullable<int> isDue { get; set; }
    
        public virtual tblBuy tblBuy { get; set; }
        public virtual tblCommonElement tblCommonElement { get; set; }
        public virtual tblSell tblSell { get; set; }
        public virtual ICollection<tblDue> tblDues { get; set; }
    }
}
