//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johan.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParty
    {
        public tblParty()
        {
            this.tblBuys = new HashSet<tblBuy>();
            this.tblCollections = new HashSet<tblCollection>();
            this.tblIncomeSources = new HashSet<tblIncomeSource>();
            this.tblPayables = new HashSet<tblPayable>();
            this.tblPayments = new HashSet<tblPayment>();
            this.tblSells = new HashSet<tblSell>();
            this.BagTransactions = new HashSet<BagTransaction>();
            this.tblDues = new HashSet<tblDue>();
            this.OpeningBalances = new HashSet<OpeningBalance>();
        }
    
        public int ID { get; set; }
        public Nullable<int> productId { get; set; }
        public string name { get; set; }
        public Nullable<long> contactNo { get; set; }
        public string area { get; set; }
        public Nullable<int> districtId { get; set; }
        public Nullable<int> zoneId { get; set; }
        public bool isCashParty { get; set; }
    
        public virtual ICollection<tblBuy> tblBuys { get; set; }
        public virtual ICollection<tblCollection> tblCollections { get; set; }
        public virtual tblCommonElement tblCommonElement { get; set; }
        public virtual ICollection<tblIncomeSource> tblIncomeSources { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public virtual ICollection<tblPayable> tblPayables { get; set; }
        public virtual ICollection<tblPayment> tblPayments { get; set; }
        public virtual ICollection<tblSell> tblSells { get; set; }
        public virtual ICollection<BagTransaction> BagTransactions { get; set; }
        public virtual ICollection<tblDue> tblDues { get; set; }
        public virtual ICollection<OpeningBalance> OpeningBalances { get; set; }
    }
}
