//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johan.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductPrice
    {
        public int ID { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
