//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johan.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSackInfo
    {
        public long ID { get; set; }
        public int partyId { get; set; }
        public Nullable<long> rcvId { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> noOfSackSent { get; set; }
        public Nullable<int> noOfSackRcvd { get; set; }
        public Nullable<double> bagPrice { get; set; }
        public Nullable<int> bagDues { get; set; }
    
        public virtual tblBuy tblBuy { get; set; }
        public virtual tblParty tblParty { get; set; }
    }
}
