//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johan.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSell
    {
        public tblSell()
        {
            this.tblCollections = new HashSet<tblCollection>();
            this.tblCostingSources = new HashSet<tblCostingSource>();
            this.tblPayables = new HashSet<tblPayable>();
            this.STK_Transaction = new HashSet<STK_Transaction>();
        }
    
        public long ID { get; set; }
        public int partyId { get; set; }
        public int productId { get; set; }
        public System.DateTime date { get; set; }
        public int noOfBag { get; set; }
        public double quantity { get; set; }
        public int unit { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public Nullable<int> stockId { get; set; }
        public Nullable<long> incSrcId { get; set; }
        public Nullable<double> transportCost { get; set; }
        public string truckNumber { get; set; }
        public string description { get; set; }
    
        public virtual STK_tblStock STK_tblStock { get; set; }
        public virtual ICollection<tblCollection> tblCollections { get; set; }
        public virtual ICollection<tblCostingSource> tblCostingSources { get; set; }
        public virtual tblIncomeSource tblIncomeSource { get; set; }
        public virtual tblParty tblParty { get; set; }
        public virtual ICollection<tblPayable> tblPayables { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public virtual ICollection<STK_Transaction> STK_Transaction { get; set; }
    }
}
