//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johan.DATA
{
    using System;
    using System.Collections.Generic;

    public partial class tblBuy
    {
        public double amount { get; set; }
        public int noOfSackRcvd { get; set; }
        public int noOfSackSent { get; set; }
        public double? bagPrice { get; set; }
        public string partyName { get; set; }
        public string productName { get; set; }     
        public string stockName { get; set; }
        public DateTime fromDate { get; set; }
        public DateTime toDate { get; set; }
        public double? transportCost { get; set; }
        public double? labourCostPerBag { get; set; }
        public bool transportCostInclude { get; set; }
    }
}
