//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johan.DATA
{
    using System;
    using System.Collections.Generic;

    public partial class tblSell
    {
        public string partyName { get; set; }
        public string productName { get; set; }
        public string stockName { get; set; }
        public double paidAmount { get; set; }
        public DateTime fromDate { get; set; }
        public DateTime toDate { get; set; }
        public bool transportCostInclude { get; set; }
        public int parentProd { set; get; }
        

    }
}
